export const {
    NODE_ENV,
    NEXT_PUBLIC_SEO_TITLE: SEO_TITLE,
    NEXT_PUBLIC_SEO_BANNER: SEO_BANNER,
    NEXT_PUBLIC_SEO_DOMAIN: SEO_DOMAIN,
    NEXT_PUBLIC_SEO_DESCRIPTION: SEO_DESCRIPTION,
    NEXT_PUBLIC_STRAPI_BASE_URL: STRAPI_BASE_URL,
} = process.env;
