name: CI

on: [push, pull_request]

jobs:
    code_integration:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install node
              uses: actions/setup-node@v1
              with:
                  node-version: 18

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - name: Check format
              run: yarn check-format

            - name: Check lint
              run: yarn check-lint

            - name: Check production build
              run: yarn build
